pages:
  only:
    - master
    - /^[0-9]*\.[0-9]*\.[0-9]*$/
  image: jbigot/doxygen
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - rm -rf build; true
    - mkdir build
    - cd build
    - cmake -DUSE_DEFAULT=EMBEDDED -DBUILD_CFG_VALIDATOR=OFF -DBUILD_DECL_HDF5_PLUGIN=OFF -DBUILD_MPI_PLUGIN=OFF -DBUILD_TESTING=OFF -DENABLE_FORTRAN=ON -DENABLE_PYTHON=ON ..
    - make doc
    - mkdir -p "../public/"
    - if [ -z "${CI_COMMIT_TAG}" ]; then mv pdi/src/PDI-build/docs/html "../public/${CI_COMMIT_REF_NAME}"; fi
    - if [ -n "${CI_COMMIT_TAG}" ]; then mv pdi/src/PDI-build/docs/html "../public/${CI_COMMIT_TAG}"; fi
  artifacts:
    paths:
      - public
