stages:
  - test
  - pages
  - external
  
cmake3.5_embedded:
  only: [ master, merge_requests ]
  image: pdidevel/centos_cmake3.5:latest
  script:
    - cmake -DDIST_PROFILE=Devel -DBUILD_DOCUMENTATION=OFF -DBUILD_TESTING=OFF .
    - make

cmake3.5_system:
  only: [ master, merge_requests ]
  image: pdidevel/centos_libs_cmake3.5:latest
  script:
    - cmake -DDIST_PROFILE=Devel -DBUILD_DOCUMENTATION=OFF -DBUILD_TESTING=OFF .
    - make

cmake3.10_embedded:
  only: [ master, merge_requests ]
  image: pdidevel/centos_cmake3.10:latest
  script:
    - cmake -DDIST_PROFILE=Devel -DUSE_DEFAULT=EMBEDDED .
    - make
    - ctest --output-on-failure

cmake3.10_system:
  only: [ master, merge_requests ]
  image: pdidevel/centos_libs_cmake3.10:latest
  script:
    - cmake -DDIST_PROFILE=Devel -DUSE_DEFAULT=SYSTEM -DUSE_Bpp=SYSTEM .
    - make
    - ctest --output-on-failure

pages:
  only: [ master, '/^[0-9]*\.[0-9]*\.[0-9]*$/' ]
  stage: pages
  image: pdidevel/centos_libs_cmake3.10:latest
  variables: { GIT_SUBMODULE_STRATEGY: recursive }
  script:
    - mkdir build
    - cd build
    - cmake -DDIST_PROFILE=User -DBUILD_DOCUMENTATION=ON -DUSE_DEFAULT=SYSTEM -DUSE_Bpp=SYSTEM ..
    - make PDI_pkg
    - cd
    - mkdir -p "$CI_PROJECT_DIR/public/"
    - if [ -z "${CI_COMMIT_TAG}" ]; then mv $CI_PROJECT_DIR/build/staging/share/doc/PDI/html "$CI_PROJECT_DIR/public/${CI_COMMIT_REF_NAME}"; fi
    - if [ -n "${CI_COMMIT_TAG}" ]; then mv $CI_PROJECT_DIR/build/staging/share/doc/PDI/html "$CI_PROJECT_DIR/public/${CI_COMMIT_TAG}"; fi
  artifacts: { paths: [ public ] }

pages-deploy:
  only: [ master, '/^[0-9]*\.[0-9]*\.[0-9]*$/' ]
  stage: .post
  script:
    - |
        curl -s -u "jbigot:${GITHUB_SITE_DEPLOY_KEY}" -H 'Accept: application/vnd.github.v3+json' -X POST "https://api.github.com/repos/pdidev/pdidev.github.io/dispatches" -d '{ "event_type": "do_gitlab_deploy" }'
