pages:
  only:
    - master
    - /^[0-9]*\.[0-9]*\.[0-9]*$/
  image: jbigot/doxygen
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - rm -rf build; true
    - mkdir build
    - cd build
    - cmake -DBUILD_DOCUMENTATION=ON -DBUILD_DECL_HDF5_PLUGIN=OFF -DBUILD_FORTRAN=OFF -DBUILD_MPI_PLUGIN=OFF ..
    - make -j 2 install
    - mkdir -p "../public/"
    - if [ -z "${CI_COMMIT_TAG}" ]; then mv staging/share/doc/PDI/html "../public/${CI_COMMIT_REF_NAME}"; fi
    - if [ -n "${CI_COMMIT_TAG}" ]; then mv staging/share/doc/PDI/html "../public/${CI_COMMIT_TAG}"; fi
  artifacts:
    paths:
      - public
